name: .NET Build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    name: Build QRCode Project
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore project dependencies
        run: dotnet restore QRCode/QRCode/QRCode.vbproj

      - name: Build project
        run: dotnet build QRCode/QRCode/QRCode.vbproj --no-restore --configuration Release
